In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
invoice_file = '/content/drive/My Drive/Datasets/newest_invoices_data.csv'
invoice_df = pd.read_csv(invoice_file)

In [4]:
employeeEarn_file = '/content/drive/My Drive/Datasets/boston_employee_data.csv'
employeeEarn_df = pd.read_csv(employeeEarn_file)

In [5]:
invoice_df.head()

,id_invoice,issuedDate,country,service,total,discount,tax,invoiceStatus,balance,dueDate,client
0,67,2023-07-10,Cuba,AI Solution,8685.46,48.85,593.26,Paid,9229.87,2023-08-03,Company B
1,57,2022-10-05,Uruguay,Mobile App Development,3196.11,437.68,131.34,Pending,2889.77,2022-10-19,Company A
2,79,2022-08-01,Liberia,UI/UX Design,294.28,48.23,7.74,Overdue,253.79,2022-08-09,Company D
3,96,2022-11-30,Mongolia,Mobile App Development,2720.38,469.24,164.15,Overdue,2415.29,2022-12-16,Company D
4,87,2023-03-16,Cyprus,E-commerce Development,2202.77,410.17,214.34,Pending,2006.94,2023-04-04,Company D

In [6]:
invoice_df.shape

(10000, 11)

In [7]:
invoice_df.isna().sum()

id_invoice       0
issuedDate       0
country          0
service          0
total            0
discount         0
tax              0
invoiceStatus    0
balance          0
dueDate          0
client           0
dtype: int64

In [8]:
employeeEarn_df.head()

,_id,NAME,DEPARTMENT_NAME,TITLE,REGULAR,RETRO,OTHER,OVERTIME,INJURED,DETAIL,QUINN_EDUCATION,TOTAL GROSS,POSTAL
0,1,"Connolly,Timothy",Boston Police Department,Police Captain/DDC,"194,382.02",NaN,"26,242.23","228,924.75",NaN,NaN,"48,595.66","498,144.66",2186.0
1,2,"Demesmin,Stanley",Boston Police Department,Police Lieutenant (Det),"174,567.48",NaN,"24,390.21","236,961.33",NaN,"19,406.55","34,913.42","490,238.99",2052.0
2,3,"Hegarty,Michael J",Boston Police Department,Police Captain/DDC,"194,382.02",NaN,"21,814.27","94,495.17",NaN,"129,146.52","48,595.66","488,433.64",2032.0
3,4,"Danilecki,John H",Boston Police Department,Police Captain,"194,137.82",NaN,"28,833.82","196,303.02",NaN,"17,724.90","48,534.68","485,534.24",2559.0
4,5,"Lanchester,Wayne",Boston Police Department,Police Captain/DDC,"194,382.02",NaN,"25,366.64","72,712.36",NaN,"138,005.35","48,595.66","479,062.03",2081.0

In [9]:
employeeEarn_df.isna().sum()

_id                    0
NAME                   0
DEPARTMENT_NAME        0
TITLE                  0
REGULAR              635
RETRO              13199
OTHER               9757
OVERTIME           17395
INJURED            24352
DETAIL             23038
QUINN_EDUCATION    24051
TOTAL GROSS            0
POSTAL                21
dtype: int64

In [10]:
employee_clean = employeeEarn_df.copy()

employee_clean.columns = (
    employee_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [11]:
employee_clean.columns.to_list()

['_id',
 'name',
 'department_name',
 'title',
 'regular',
 'retro',
 'other',
 'overtime',
 'injured',
 'detail',
 'quinn_education',
 'total_gross',
 'postal']

In [12]:
money_cols = [
    "regular",
    "retro",
    "other",
    "overtime",
    "injured",
    "detail",
    "quinn_education",
    "total_gross"
]

In [13]:
def clean_money_column(series):
    return (
        series
        .astype(str)
        .str.strip()
        .str.replace(",", "", regex=False)
        .str.replace("$", "", regex=False)
        .replace(["nan", "None", "", " "], np.nan)
        .pipe(pd.to_numeric, errors="coerce")
    )

for col in money_cols:
    employee_clean[col] = clean_money_column(employee_clean[col])

# Fill missing pay component columns with 0
pay_component_cols = [
    "regular",
    "retro",
    "other",
    "overtime",
    "injured",
    "detail",
    "quinn_education"
]

In [14]:
employee_clean[pay_component_cols] = employee_clean[pay_component_cols].fillna(0)

In [15]:
text_cols = ["name", "department_name", "title"]

for col in text_cols:
    employee_clean[col] = employee_clean[col].astype(str).str.strip()

In [16]:
employee_clean["postal"] = employee_clean["postal"].astype(str).str.strip()

In [17]:
employee_clean["total_gross"].isna().sum()

np.int64(0)

In [18]:
employee_clean

,_id,name,department_name,title,regular,retro,other,overtime,injured,detail,quinn_education,total_gross,postal
0,1,"Connolly,Timothy",Boston Police Department,Police Captain/DDC,194382.02,0.00,26242.23,228924.75,0.0,0.00,48595.66,498144.66,2186.0
1,2,"Demesmin,Stanley",Boston Police Department,Police Lieutenant (Det),174567.48,0.00,24390.21,236961.33,0.0,19406.55,34913.42,490238.99,2052.0
2,3,"Hegarty,Michael J",Boston Police Department,Police Captain/DDC,194382.02,0.00,21814.27,94495.17,0.0,129146.52,48595.66,488433.64,2032.0
3,4,"Danilecki,John H",Boston Police Department,Police Captain,194137.82,0.00,28833.82,196303.02,0.0,17724.90,48534.68,485534.24,2559.0
4,5,"Lanchester,Wayne",Boston Police Department,Police Captain/DDC,194382.02,0.00,25366.64,72712.36,0.0,138005.35,48595.66,479062.03,2081.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25392,25393,"Clark,Gavin Matthew",BPS Substitute Teachers/Nurs,Substitute Teacher,0.00,14.04,0.00,0.00,0.0,0.00,0.00,14.04,2127.0
25393,25394,"McManus,Melanie Claire",BPS Substitute Teachers/Nurs,Substitute Teacher,0.00,14.04,0.00,0.00,0.0,0.00,0.00,14.04,2445.0
25394,25395,"Sullivan,Aidan Patrick",BPS Substitute Teachers/Nurs,Substitute Teacher,0.00,13.69,0.00,0.00,0.0,0.00,0.00,13.69,2130.0
25395,25396,"Corey,Lela",BPS Substitute Teachers/Nurs,Substitute Teacher,0.00,13.34,0.00,0.00,0.0,0.00,0.00,13.34,2132.0
25396,25397,"Marshall,Mairen",BPS Substitute Teachers/Nurs,Substitute Teacher,0.00,11.67,0.00,0.00,0.0,0.00,0.00,11.67,2129.0

In [19]:
employee_clean.to_csv("boston_employee.csv", index=False)